In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

#Suppress warnings
import warnings
warnings.filterwarnings("ignore")

digits= load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(digits.data, digits.target, test_size=0.3)

In [3]:
lr= LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\PC-020\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9629629629629629

In [4]:
svm= SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9888888888888889

In [5]:
rf= RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9629629629629629

In [6]:
from sklearn.model_selection import KFold
kf= KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [9]:
#get_score(SVC(), X_train, X_test, y_train, y_test)

In [10]:
from sklearn.model_selection import StratifiedKFold
folds= StratifiedKFold(n_splits=3)

In [11]:
scores_l= []
scores_svm= []
scores_rf= []

for train_index, test_index in kf.split(digits.data):
     X_train, X_test, y_train, y_test= digits.data[train_index], digits.data[test_index], \
        digits.target[train_index], digits.target[test_index]
        
scores_l.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

C:\Users\PC-020\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
scores_l

[0.9148580968280468]

In [13]:
scores_svm

[0.9549248747913188]

In [14]:
scores_rf

[0.9265442404006677]

In [15]:
from sklearn.model_selection import cross_val_score

In [19]:
scores_lr= cross_val_score(LogisticRegression(), digits.data, digits.target, cv=5)
scores_lr

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [20]:
scores_lr.mean()

0.9137650882079852

In [24]:
score_svc= cross_val_score(SVC(), digits.data, digits.target, cv=5)
score_svc

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [25]:
score_svc.mean()

0.9632838130609718

In [22]:
score_rf= cross_val_score(RandomForestClassifier(), digits.data, digits.target, cv=5)
score_rf

array([0.94444444, 0.91111111, 0.94986072, 0.96100279, 0.91643454])

In [23]:
score_rf.mean()

0.9365707211389663

# Checking Cross validation scores without the cv arguement

In [26]:
scores_lr= cross_val_score(LogisticRegression(), digits.data, digits.target)
scores_lr.mean()

0.9137650882079852

In [27]:
score_svc= cross_val_score(SVC(), digits.data, digits.target)
score_svc.mean()

0.9632838130609718

In [28]:
score_rf= cross_val_score(RandomForestClassifier(), digits.data, digits.target)
score_rf.mean()

0.9399195295574125

# Tuning parameters for Random Forest Classifier

In [35]:
score_rf= cross_val_score(RandomForestClassifier(n_estimators=10), digits.data, digits.target, cv=5)
score_rf.mean()

0.8998638192510059

In [36]:
score_rf= cross_val_score(RandomForestClassifier(n_estimators=15), digits.data, digits.target, cv=5)
score_rf.mean()

0.9104240173320953

In [37]:
score_rf= cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=5)
score_rf.mean()

0.9315738161559889

In [45]:
score_rf= cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)
score_rf.mean()

0.9360198081089447

In [38]:
score_rf= cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target, cv=5)
score_rf.mean()

0.9315784586815228

In [44]:
score_rf= cross_val_score(RandomForestClassifier(n_estimators=50), digits.data, digits.target)
score_rf.mean()

0.9326864747756114

In [39]:
score_rf= cross_val_score(RandomForestClassifier(n_estimators=60), digits.data, digits.target, cv=5)
score_rf.mean()

0.9354658000619004

In [43]:
score_rf= cross_val_score(RandomForestClassifier(n_estimators=60), digits.data, digits.target)
score_rf.mean()

0.9371262766945219

In [40]:
score_rf= cross_val_score(RandomForestClassifier(n_estimators=100), digits.data, digits.target, cv=5)
score_rf.mean()

0.9388099659548128

In [41]:
score_rf= cross_val_score(RandomForestClassifier(n_estimators=100), digits.data, digits.target)
score_rf.mean()

0.936027545651501

In [46]:
score_rf= cross_val_score(RandomForestClassifier(n_estimators=200), digits.data, digits.target, cv=5)
score_rf.mean()

0.9371432992881461

In [48]:
score_rf= cross_val_score(RandomForestClassifier(n_estimators=200), digits.data, digits.target)
score_rf.mean()

0.9376973073351904