In [1]:
#pip install faiss-cpu
#pip install sentence-transformers

In [51]:
import pandas as pd

pd.set_option("display.max_colwidth", 100)

In [108]:
df= pd.read_csv('ecommerceDataset.csv', names= ["label", "text"])
df[:5]

label  \
0  Household   
1  Household   
2  Household   
3  Household   
4  Household   

                                                                                                  text  
0  Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - S...  
1  SAF 'Floral' Framed Painting (Wood, 30 inch x 10 inch, Special Effect UV Print Textured, SAO297)...  
2  SAF 'UV Textured Modern Art Print Framed' Painting (Synthetic, 35 cm x 50 cm x 3 cm, Set of 3) C...  
3  SAF Flower Print Framed Painting (Synthetic, 13.5 inch x 22 inch, UV Textured, Set of 3, SANFSW4...  
4  Incredible Gifts India Wooden Happy Birthday Unique Personalized Gift (5 X 4 Inch) Size:4 x 5   ...

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50425 entries, 0 to 50424
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   label   50425 non-null  object
 1   text    50424 non-null  object
dtypes: object(2)
memory usage: 788.0+ KB


In [78]:
df.dropna(inplace=True)

In [79]:
df= df.head(10)
df

label  \
0  Household   
1  Household   
2  Household   
3  Household   
4  Household   
5  Household   
6  Household   
7  Household   
8  Household   
9  Household   

                                                                                                  text  
0  Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - S...  
1  SAF 'Floral' Framed Painting (Wood, 30 inch x 10 inch, Special Effect UV Print Textured, SAO297)...  
2  SAF 'UV Textured Modern Art Print Framed' Painting (Synthetic, 35 cm x 50 cm x 3 cm, Set of 3) C...  
3  SAF Flower Print Framed Painting (Synthetic, 13.5 inch x 22 inch, UV Textured, Set of 3, SANFSW4...  
4  Incredible Gifts India Wooden Happy Birthday Unique Personalized Gift (5 X 4 Inch) Size:4 x 5   ...  
5  Pitaara Box Romantic Venice Canvas Painting 6mm Thick Mdf Frame 21.1 X 14Inch Enclosure Material...  
6  Paper Plane Design Starry Night Vangoh Wall Art Canvas Painting. Large Size Rolled Canvas Art Pr...  
7  Pitaara Box Romantic Venice Canvas Painting 6mm Thick Mdf Frame 21.1 X 14Inch Enclosure Material...  
8  SAF 'Ganesh Modern Art Print' Painting (Synthetic, 35 cm x 50 cm x 2 cm, Set of 3) Color:Multico...  
9  Paintings Villa UV Textured Modern Art Print Framed Painting Home Decoration - Size 35 X 2 X 50 ...

In [92]:
df.value_counts()

label      text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

In [58]:
from sentence_transformers import SentenceTransformer

In [59]:
encoder= SentenceTransformer("all-mpnet-base-v2")

C:\Users\Open user\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Open user\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


In [82]:
df.text[:4]

0    Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - S...
1    SAF 'Floral' Framed Painting (Wood, 30 inch x 10 inch, Special Effect UV Print Textured, SAO297)...
2    SAF 'UV Textured Modern Art Print Framed' Painting (Synthetic, 35 cm x 50 cm x 3 cm, Set of 3) C...
3    SAF Flower Print Framed Painting (Synthetic, 13.5 inch x 22 inch, UV Textured, Set of 3, SANFSW4...
Name: text, dtype: object

In [80]:
#Converting text to embeddings or vectors
vectors= encoder.encode(df.text)

In [83]:
vectors

array([[ 0.03981813, -0.05984238,  0.0075271 , ...,  0.01086954,
        -0.01929882, -0.01068373],
       [ 0.04453882, -0.07820097, -0.01965575, ...,  0.02906194,
         0.02570836, -0.02267086],
       [ 0.04448814, -0.04873287, -0.01433982, ...,  0.01617706,
         0.00663231, -0.00404146],
       ...,
       [ 0.02787285, -0.05495737, -0.0217257 , ..., -0.00507688,
        -0.02009064, -0.0254602 ],
       [ 0.03154512, -0.01689737, -0.01772535, ...,  0.02631624,
         0.00208247, -0.04307628],
       [ 0.0182513 , -0.07885455, -0.0058034 , ...,  0.00665323,
        -0.01786171, -0.02828166]], dtype=float32)

In [85]:
vectors.shape

(10, 768)

In [88]:
vector_dim= vectors.shape[1]
vector_dim

768

In [90]:
import faiss

#Creating index of size 768
index= faiss.IndexFlatL2(vector_dim)                     #It creates index that allows fast similarity search
index

<faiss.swigfaiss.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x000001E5A99C9920> >

In [91]:
index.add(vectors)

In [93]:
query= "Those beautiful gowns are my favourites"

vec= encoder.encode(query)
vec.shape

(768,)

In [94]:
import numpy as np

#Converting the above 1D array to 2D array
reshaped_vec= np.array(vec).reshape(1, -1)
reshaped_vec.shape

(1, 768)

In [98]:
#This expects 2D arrays
index.search(reshaped_vec, k=3)  

(array([[1.4567852, 1.495304 , 1.5098816]], dtype=float32),
 array([[1, 3, 9]], dtype=int64))

In [99]:
distance, I= index.search(reshaped_vec, k=3)

In [100]:
I

array([[1, 3, 9]], dtype=int64)

In [101]:
distance

array([[1.4567852, 1.495304 , 1.5098816]], dtype=float32)

In [103]:
df.loc[[1,3,9]]

label  \
1  Household   
3  Household   
9  Household   

                                                                                                  text  
1  SAF 'Floral' Framed Painting (Wood, 30 inch x 10 inch, Special Effect UV Print Textured, SAO297)...  
3  SAF Flower Print Framed Painting (Synthetic, 13.5 inch x 22 inch, UV Textured, Set of 3, SANFSW4...  
9  Paintings Villa UV Textured Modern Art Print Framed Painting Home Decoration - Size 35 X 2 X 50 ...

In [109]:
df.loc[I[0]]

label  \
1  Household   
3  Household   
9  Household   

                                                                                                  text  
1  SAF 'Floral' Framed Painting (Wood, 30 inch x 10 inch, Special Effect UV Print Textured, SAO297)...  
3  SAF Flower Print Framed Painting (Synthetic, 13.5 inch x 22 inch, UV Textured, Set of 3, SANFSW4...  
9  Paintings Villa UV Textured Modern Art Print Framed Painting Home Decoration - Size 35 X 2 X 50 ...

In [105]:
df.text[1]

"SAF 'Floral' Framed Painting (Wood, 30 inch x 10 inch, Special Effect UV Print Textured, SAO297) Painting made up in synthetic frame with UV textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch (A perfect gift for your special ones)."

In [106]:
df.text[3]

'SAF Flower Print Framed Painting (Synthetic, 13.5 inch x 22 inch, UV Textured, Set of 3, SANFSW4951) Color:Multicolor                                                                                \xa0|\xa0                           Size:35 cm x 50 cm x 2 cm   A beautiful painting involves the action or skill of using paint in the right manner, hence, the end product will be a picture that can speak a thousand words they say. Arts have been in trend for quite some time now. It can give different viewer different meanings style and design the saf wood matte painting with frame is quite abstract and mysteriously beautiful. The painting has a nice frame to it. You can gift this to a family or a friend. The painting has various forms of certain figures on it as seen in the image. You can add a good set of lights to the place where the painting is and the decor will give a different feel and look to the place. Quality and durability the painting has a matte finish and includes a good quali

In [107]:
df.text[9]

"Paintings Villa UV Textured Modern Art Print Framed Painting Home Decoration - Size 35 X 2 X 50 cm Paintings Villa UV Textured Modern Art Print Framed Painting Home Decoration - Size 35 X 2 X 50 cm Decorate your home and office walls with these artistic design satin matt texture framed UV art print from MAV. Each design reflects the artistic qualities and time one has taken to design this poster. Exquisitely printed and framed it is also a perfect gifting option for your colleagues loved ones and family members. These frames don't include glass so it is very light weight and wet cloth can be used to clean it."